interactiveShell: interactiveShell.o
		g++ -o interactiveShell  interactiveShell.o

interactiveShell.o: interactiveShell.cpp
		g++  -c interactiveShell.cpp -o interactiveShell.o

clean:
		rm -f interactiveShell.o interactiveShell
